export const MOCK_QUESTIONS = [
  {
    id: 1,
    number: 1,
    subject: 'Educación Vial',
    topic: 'Señales de Tránsito',
    license_category: 'A-I',
    question: '¿Qué indica una señal de tránsito vertical de forma octogonal con fondo de color rojo y letras blancas que dice "PARE"?',
    image_url: null,
    explanation: 'La señal R-1 (PARE) obliga al conductor a detener por completo su vehículo en la línea de parada antes de ingresar a la intersección.',
    options: [
      { id: 101, option_number: 1, option_text: 'Detención obligatoria y total del vehículo antes de la línea de parada.', is_correct: true },
      { id: 102, option_number: 2, option_text: 'Disminuir la velocidad y continuar solo si no vienen peatones.', is_correct: false },
      { id: 103, option_number: 3, option_text: 'Ceder el paso únicamente a vehículos pesados.', is_correct: false },
      { id: 104, option_number: 4, option_text: 'Acelerar para cruzar la intersección rápidamente.', is_correct: false },
    ],
  },
  {
    id: 2,
    number: 2,
    subject: 'Normas de Conducción',
    topic: 'Prioridad de Paso',
    license_category: 'A-I',
    question: 'En una intersección no semaforizada sin señales de prioridad, ¿quién tiene preferencia de paso entre dos vehículos que convergen?',
    image_url: null,
    explanation: 'En intersecciones no reguladas, la preferencia la tiene el vehículo que se aproxima por la derecha del conductor.',
    options: [
      { id: 105, option_number: 1, option_text: 'El vehículo que aparece por el lado derecho del conductor.', is_correct: true },
      { id: 106, option_number: 2, option_text: 'El vehículo de mayor tamaño o cilindraje.', is_correct: false },
      { id: 107, option_number: 3, option_text: 'El que toque la bocina primero.', is_correct: false },
      { id: 108, option_number: 4, option_text: 'El vehículo que transita por la izquierda.', is_correct: false },
    ],
  },
  {
    id: 3,
    number: 3,
    subject: 'Límites de Velocidad',
    topic: 'Reglamento Nacional',
    license_category: 'A-I',
    question: 'Según la normativa del MTC, ¿cuál es la velocidad máxima permitida en calles y jirones de zonas urbanas salvo señalización en contrario?',
    image_url: null,
    explanation: 'El Decreto Supremo 025-2021-MTC estableció que el límite máximo en calles y jirones es de 30 km/h y en avenidas 50 km/h.',
    options: [
      { id: 109, option_number: 1, option_text: '30 km/h.', is_correct: true },
      { id: 110, option_number: 2, option_text: '40 km/h.', is_correct: false },
      { id: 111, option_number: 3, option_text: '50 km/h.', is_correct: false },
      { id: 112, option_number: 4, option_text: '60 km/h.', is_correct: false },
    ],
  },
  {
    id: 4,
    number: 4,
    subject: 'Seguridad Vial',
    topic: 'Rotondas',
    license_category: 'A-I',
    question: 'En una rotonda u óvalo, ¿quién tiene derecho preferente de paso?',
    image_url: null,
    explanation: 'Tiene prioridad de paso el vehículo que ya se encuentra circulando dentro de la calzada de la rotonda sobre el que intenta ingresar.',
    options: [
      { id: 113, option_number: 1, option_text: 'El vehículo que ya circula dentro de la rotonda.', is_correct: true },
      { id: 114, option_number: 2, option_text: 'El vehículo que intenta ingresar a la rotonda.', is_correct: false },
      { id: 115, option_number: 3, option_text: 'El vehículo que circula a mayor velocidad.', is_correct: false },
      { id: 116, option_number: 4, option_text: 'Cualquier vehículo que utilice luces intermitentes.', is_correct: false },
    ],
  },
  {
    id: 5,
    number: 5,
    subject: 'Mecánica y Emergencias',
    topic: 'Uso de Luces',
    license_category: 'A-I',
    question: '¿Cuándo es obligatorio el uso de las luces intermitentes de emergencia (hazard)?',
    image_url: null,
    explanation: 'Las luces de emergencia deben emplearse para alertar a otros usuarios cuando el vehículo está detenido por desperfecto o en maniobras de emergencia.',
    options: [
      { id: 117, option_number: 1, option_text: 'Cuando el vehículo esté inmovilizado en la vía por emergencia o avería.', is_correct: true },
      { id: 118, option_number: 2, option_text: 'Para estacionarse en zonas rígidas momentáneamente.', is_correct: false },
      { id: 119, option_number: 3, option_text: 'Durante toda la noche en carreteras iluminadas.', is_correct: false },
      { id: 120, option_number: 4, option_text: 'Para avanzar más rápido en congestión vehicular.', is_correct: false },
    ],
  },
  {
    id: 6,
    number: 6,
    subject: 'Normativa MTC',
    topic: 'Documentación Obligatoria',
    license_category: 'A-I',
    question: '¿Cuáles son los documentos que todo conductor debe portar obligatoriamente al conducir un vehículo en la vía pública?',
    image_url: null,
    explanation: 'Es mandatorio portar: Licencia de Conducir vigente, Tarjeta de Identificación Vehicular, SOAT vigente y Certificado de Inspección Técnica Vehicular (CITV).',
    options: [
      { id: 121, option_number: 1, option_text: 'Licencia de conducir vigente, Tarjeta de Identificación Vehicular, SOAT vigente y CITV.', is_correct: true },
      { id: 122, option_number: 2, option_text: 'Únicamente el DNI y la copia simple de la licencia.', is_correct: false },
      { id: 123, option_number: 3, option_text: 'Contrato de compraventa y carnet de vacunación.', is_correct: false },
      { id: 124, option_number: 4, option_text: 'Factura del vehículo y póliza de seguro contra todo riesgo.', is_correct: false },
    ],
  },
  {
    id: 7,
    number: 7,
    subject: 'Primeros Auxilios',
    topic: 'Accidentes de Tránsito',
    license_category: 'A-I',
    question: 'En caso de presenciar o verse involucrado en un accidente de tránsito con personas lesionadas, ¿cuál es la primera acción que debe realizar?',
    image_url: null,
    explanation: 'El protocolo PAS: Proteger el lugar del accidente, Avisar a las autoridades y emergencias (116 o 105), y Socorrer con precaución.',
    options: [
      { id: 125, option_number: 1, option_text: 'Asegurar la zona para evitar más colisiones y llamar inmediatamente a emergencias (116 / 105).', is_correct: true },
      { id: 126, option_number: 2, option_text: 'Mover bruscamente a los heridos para sacarlos del vehículo.', is_correct: false },
      { id: 127, option_number: 3, option_text: 'Abandonar el lugar si no fue el causante directo del siniestro.', is_correct: false },
      { id: 128, option_number: 4, option_text: 'Ofrecer medicamentos o agua a las personas inconscientes.', is_correct: false },
    ],
  },
  {
    id: 8,
    number: 8,
    subject: 'Educación Vial',
    topic: 'Líneas y Marcas en el Pavimento',
    license_category: 'A-I',
    question: '¿Qué significado tiene una línea longitudinal continua de color amarillo en el centro de la calzada?',
    image_url: null,
    explanation: 'La línea continua amarilla indica la separación de sentidos de tránsito y PROHÍBE el adelantamiento o cruce de dicha línea.',
    options: [
      { id: 129, option_number: 1, option_text: 'Prohíbe terminantemente el adelantamiento o invasión del carril contrario.', is_correct: true },
      { id: 130, option_number: 2, option_text: 'Permite adelantar siempre que no vengan peatones.', is_correct: false },
      { id: 131, option_number: 3, option_text: 'Indica carril exclusivo para transporte público.', is_correct: false },
      { id: 132, option_number: 4, option_text: 'Zona para estacionamiento provisional.', is_correct: false },
    ],
  },
];

export const MOCK_DISCUSSIONS = [
  {
    id: 1,
    user_id: 1,
    title: '¿Cuál es la velocidad máxima en zonas escolares y hospitalarias?',
    content: 'Tengo dudas para el examen de A-I. ¿La velocidad máxima permitida frente a colegios en horario escolar sigue siendo 30 km/h?',
    image_url: null,
    status: 'open',
    closed_by_user_id: null,
    closed_reason: null,
    created_at: new Date(Date.now() - 3600000 * 4).toISOString(),
    author: { id: 1, name: 'Carlos Mendoza' },
  },
  {
    id: 2,
    user_id: 2,
    title: 'Prioridad de paso en intersecciones con semáforo intermitente ámbar',
    content: 'Cuando el semáforo está parpadeando en luz ámbar, ¿se debe parar por completo o cruzar con precaución?',
    image_url: null,
    status: 'closed',
    closed_by_user_id: 1,
    closed_reason: 'Respondido de acuerdo al Art. 101 del Reglamento MTC: circular con precaución reduciendo la velocidad.',
    created_at: new Date(Date.now() - 3600000 * 24).toISOString(),
    author: { id: 2, name: 'Lucía Torres' },
  },
  {
    id: 3,
    user_id: 3,
    title: 'Diferencia entre señal R-1 (Pare) y R-2 (Ceda el Paso)',
    content: 'Muchos postulantes fallan en esta pregunta. ¿En el Ceda el Paso es obligatorio detenerse al 100% como en el Pare?',
    image_url: null,
    status: 'open',
    closed_by_user_id: null,
    closed_reason: null,
    created_at: new Date(Date.now() - 3600000 * 48).toISOString(),
    author: { id: 3, name: 'David Quispe' },
  },
];

export const MOCK_RECOMMENDATIONS = [
  {
    id: 1,
    title: 'Regla de los 3 Segundos de Distancia',
    category: 'Seguridad Vial',
    content: 'Conserva al menos 3 segundos de separación con el vehículo que te antecede en condiciones normales, y amplíala a 5 segundos bajo lluvia o niebla densa.',
    image_url: null,
    is_active: true,
    created_at: '2026-01-15T09:00:00.000Z',
  },
  {
    id: 2,
    title: 'Conducción a la Defensiva en Intersecciones',
    category: 'Seguridad Vial',
    content: 'Aun con luz verde a tu favor, mira a la izquierda y derecha antes de cruzar. Muchos accidentes ocurren por conductores que no respetan el cambio de luz.',
    image_url: null,
    is_active: true,
    created_at: '2026-01-16T10:30:00.000Z',
  },
  {
    id: 3,
    title: 'Límites de Velocidad Actualizados (DS 025-2021-MTC)',
    category: 'Normas de Tránsito',
    content: 'Recuerda: 30 km/h en calles y jirones; 50 km/h en avenidas urbanas; 30 km/h en zonas escolares y comerciales.',
    image_url: null,
    is_active: true,
    created_at: '2026-01-17T11:00:00.000Z',
  },
  {
    id: 4,
    title: 'Revisión Preventiva de Neumáticos y Frenos',
    category: 'Mecánica Básica',
    content: 'Verifica la presión de los neumáticos al menos una vez al mes y asegúrate de que el dibujo de la banda de rodadura tenga una profundidad mínima de 1.6 mm.',
    image_url: null,
    is_active: true,
    created_at: '2026-01-18T14:15:00.000Z',
  },
  {
    id: 5,
    title: 'Puntos Ciegos y Ajuste Óptimo de Espejos',
    category: 'Seguridad Vial',
    content: 'Ajusta los espejos laterales de modo que apenas alcances a ver el borde trasero de tu propio vehículo. Esto maximiza la visibilidad en carriles contiguos.',
    image_url: null,
    is_active: true,
    created_at: '2026-01-19T16:00:00.000Z',
  },
  {
    id: 6,
    title: 'Protocolo PAS ante Siniestros Viales',
    category: 'Primeros Auxilios',
    content: 'Proteger: asegura el perímetro con triángulos reflectivos a 50m. Avisar: llama al 116 (Bomberos) o 105 (Policía). Socorrer: no muevas a heridos graves si no hay riesgo de incendio.',
    image_url: null,
    is_active: true,
    created_at: '2026-01-20T17:45:00.000Z',
  },
];
